/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Glasgow;

/**
 *
 * @author Gabriel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        next = new javax.swing.JButton();
        back = new javax.swing.JButton();
        menu = new javax.swing.JTabbedPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        fazerEscalar = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        aoNivel4 = new javax.swing.JRadioButton();
        aoNivel3 = new javax.swing.JRadioButton();
        aoNivel2 = new javax.swing.JRadioButton();
        aoNivel1 = new javax.swing.JRadioButton();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        mrvNivel5 = new javax.swing.JRadioButton();
        mrvNivel4 = new javax.swing.JRadioButton();
        mrvNivel3 = new javax.swing.JRadioButton();
        mrvNivel2 = new javax.swing.JRadioButton();
        mrvNivel1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        mrmNivel6 = new javax.swing.JRadioButton();
        mrmNivel5 = new javax.swing.JRadioButton();
        mrmNivel4 = new javax.swing.JRadioButton();
        mrmNivel3 = new javax.swing.JRadioButton();
        mrmNivel2 = new javax.swing.JRadioButton();
        mrmNivel1 = new javax.swing.JRadioButton();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        classificacao = new javax.swing.JLabel();
        totalPonto = new javax.swing.JLabel();
        situacao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escala de coma de Glasgow");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        next.setText("Proximo");
        next.setVisible(false);
        next.setEnabled(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jDesktopPane1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        back.setText("Voltar");
        back.setVisible(false);
        back.setEnabled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jDesktopPane1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 80, -1));

        jDesktopPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(), "MENU", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        fazerEscalar.setText("Fazer a escalar de coma Glasgow");
        fazerEscalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazerEscalarActionPerformed(evt);
            }
        });

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(fazerEscalar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(sair, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fazerEscalar)
                    .addComponent(sair))
                .addGap(203, 203, 203))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(fazerEscalar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sair)
                .addGap(74, 74, 74))
        );

        menu.addTab("Menu", jDesktopPane2);

        jDesktopPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(), "Abertura Ocular (AO)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        buttonGroup1.add(aoNivel4);
        aoNivel4.setText("Olhos se abrem espontaneamente.");
        aoNivel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoNivel4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(aoNivel3);
        aoNivel3.setText("Olhos se abrem ao comando verbal.");
        aoNivel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoNivel3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(aoNivel2);
        aoNivel2.setText("Olhos se abrem por estímulo doloroso. ");
        aoNivel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoNivel2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(aoNivel1);
        aoNivel1.setText("Olhos não se abrem por nenhum motivo. ");
        aoNivel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoNivel1ActionPerformed(evt);
            }
        });

        jDesktopPane3.setLayer(aoNivel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(aoNivel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(aoNivel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(aoNivel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aoNivel1)
                    .addComponent(aoNivel2)
                    .addComponent(aoNivel3)
                    .addComponent(aoNivel4))
                .addGap(0, 368, Short.MAX_VALUE))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addComponent(aoNivel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aoNivel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aoNivel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aoNivel1)
                .addGap(0, 99, Short.MAX_VALUE))
        );

        menu.addTab("AO", jDesktopPane3);

        jDesktopPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(), "Melhor resposta verbal (MRV)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        buttonGroup2.add(mrvNivel5);
        mrvNivel5.setText("Orientado: O paciente responde coerentemente e apropriadamente às perguntas sobre seu nome e idade, ");
        mrvNivel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrvNivel5ActionPerformed(evt);
            }
        });

        buttonGroup2.add(mrvNivel4);
        mrvNivel4.setText("Confuso: O paciente responde às perguntas coerentemente, mas com alguma desorientação e confusão .");
        mrvNivel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrvNivel4ActionPerformed(evt);
            }
        });

        buttonGroup2.add(mrvNivel3);
        mrvNivel3.setText("Palavras inapropriadas: Fala aleatória, mas sem troca conversacional .");
        mrvNivel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrvNivel3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(mrvNivel2);
        mrvNivel2.setText("Sons ininteligíveis: Gemendo, grunhindo e sem articular palavras.");
        mrvNivel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrvNivel2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(mrvNivel1);
        mrvNivel1.setText("Ausente: Não emite nenhum som .");
        mrvNivel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrvNivel1ActionPerformed(evt);
            }
        });

        jLabel1.setText("onde está e por quê, a data etc.");

        jDesktopPane4.setLayer(mrvNivel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(mrvNivel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(mrvNivel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(mrvNivel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(mrvNivel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mrvNivel5, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mrvNivel1)
                    .addComponent(mrvNivel3)
                    .addComponent(mrvNivel4)
                    .addComponent(mrvNivel2)
                    .addGroup(jDesktopPane4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addComponent(mrvNivel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mrvNivel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mrvNivel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mrvNivel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mrvNivel1)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        menu.addTab("MRV", jDesktopPane4);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(), "Melhor resposta motora (MRM)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        buttonGroup3.add(mrmNivel6);
        mrmNivel6.setText("Obedece ordens verbais: O paciente faz coisas simples quando lhe é ordenado.");
        mrmNivel6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrmNivel6ActionPerformed(evt);
            }
        });

        buttonGroup3.add(mrmNivel5);
        mrmNivel5.setText("Localiza estímulo doloroso.");
        mrmNivel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrmNivel5ActionPerformed(evt);
            }
        });

        buttonGroup3.add(mrmNivel4);
        mrmNivel4.setText("Retirada inespecífica à dor. ");
        mrmNivel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrmNivel4ActionPerformed(evt);
            }
        });

        buttonGroup3.add(mrmNivel3);
        mrmNivel3.setText("Padrão flexor à dor: Decorticação.");
        mrmNivel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrmNivel3ActionPerformed(evt);
            }
        });

        buttonGroup3.add(mrmNivel2);
        mrmNivel2.setText("Padrão extensor à dor: Descerebração.");
        mrmNivel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrmNivel2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(mrmNivel1);
        mrmNivel1.setText("Sem ou nenhuma resposta motora. ");
        mrmNivel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrmNivel1ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(mrmNivel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mrmNivel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mrmNivel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mrmNivel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mrmNivel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mrmNivel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mrmNivel1)
                    .addComponent(mrmNivel2)
                    .addComponent(mrmNivel3)
                    .addComponent(mrmNivel4)
                    .addComponent(mrmNivel5)
                    .addComponent(mrmNivel6))
                .addGap(0, 175, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(mrmNivel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mrmNivel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mrmNivel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mrmNivel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mrmNivel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mrmNivel1)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        menu.addTab("MRM", jLayeredPane1);

        jDesktopPane5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(), "Resultado:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        classificacao.setText("Classificacao");

        totalPonto.setText("Total");

        situacao.setText("Situacao");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Situação:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Classificação:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Total:");

        backMenu.setText("Voltar Menu");
        backMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuActionPerformed(evt);
            }
        });

        jDesktopPane5.setLayer(classificacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(totalPonto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(situacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(backMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane5Layout.createSequentialGroup()
                        .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalPonto)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classificacao))
                    .addGroup(jDesktopPane5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(situacao))
                    .addComponent(backMenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(situacao)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classificacao)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPonto)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backMenu)
                .addGap(13, 13, 13))
        );

        menu.addTab("Resultado", jDesktopPane5);

        jDesktopPane1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 620, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fazerEscalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazerEscalarActionPerformed
        // TODO add your handling code here:
        
        //next.setEnabled(true);
        next.setVisible(true);
        back.setVisible(true);
        back.setEnabled(true);
        
        if(getAONivel() == 0)
            next.setEnabled(false);
        
        menu.setSelectedIndex(1); 
    }//GEN-LAST:event_fazerEscalarActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed
    
    
    
    
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        int index = menu.getSelectedIndex(); 
        
            next.setEnabled(false);
            
            if(index+1 == 4)
            {
                back.setVisible(false);
                next.setVisible(false);
            }
            
            if(index == 0 && getAONivel() != 0)
                next.setEnabled(true);
            if(index == 1 && getNivelMRV() != 0)
                next.setEnabled(true);
            if(index == 2 && getNivelMRM() != 0)
                next.setEnabled(true);
            
            menu.setSelectedIndex(index+1);
        //menu.setSelectedIndex(index+1);
        
        int total;
        String pontuacao = "";
        String trauma  = "";
        total = getAONivel() + getNivelMRV() + getNivelMRM();  
        
        if(total == 3)
            pontuacao = "Coma profundo sem qualquer resposta.";
        else if(total >= 4 && total < 7)
            pontuacao = " Coma profundo com provável comprometimento do diencéfalo.";
        else if(total >= 7 && total < 11)
            pontuacao = "Coma moderado.";
        else if(total >= 11 && total < 15)
            pontuacao = "Coma superficial.";
        else if(total == 15)
            pontuacao = "Normalidade.";
                
        if(total >= 3 && total <= 8)
                trauma = "Grave, com necessidade de intubação imediata.";
        else if(total >= 9 && total <= 12)
                trauma = "Moderado.";
        else if(total >= 13 && total <= 15)
                trauma = "Leve.";
        
        situacao.setText(pontuacao);
        classificacao.setText(trauma);
        totalPonto.setText(String.valueOf(total));
    }//GEN-LAST:event_nextActionPerformed
    
    public int nivelAO;
    public int nivelMRV;
    public int nivelMRM;
    
    public void setAONivel(int Nivel)
    {
        nivelAO = Nivel;
        next.setEnabled(true);
    }
    
    public int getAONivel()
    {
        return nivelAO;
    }
    
    public void setNivelMRV(int Nivel)
    {
        nivelMRV = Nivel;
        next.setEnabled(true);
    }
    
    public int getNivelMRV()
    {
        return nivelMRV;
    }
    
    public void setNivelMRM(int Nivel)
    {
        nivelMRM = Nivel;
        next.setEnabled(true);
    }
    
    public int getNivelMRM()
    {
        return nivelMRM;
    }
    
    private void aoNivel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoNivel4ActionPerformed
        // TODO add your handling code here:
        setAONivel(4);
    }//GEN-LAST:event_aoNivel4ActionPerformed

    private void aoNivel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoNivel3ActionPerformed
        // TODO add your handling code here:
        setAONivel(3);
    }//GEN-LAST:event_aoNivel3ActionPerformed

    private void aoNivel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoNivel2ActionPerformed
        // TODO add your handling code here:
        setAONivel(2);
    }//GEN-LAST:event_aoNivel2ActionPerformed

    private void aoNivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoNivel1ActionPerformed
        // TODO add your handling code here:
        setAONivel(1);//AONivel(1);
    }//GEN-LAST:event_aoNivel1ActionPerformed

    private void mrmNivel6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrmNivel6ActionPerformed
        // TODO add your handling code here:
        setNivelMRM(6);
    }//GEN-LAST:event_mrmNivel6ActionPerformed

    private void mrmNivel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrmNivel5ActionPerformed
        // TODO add your handling code here:
        setNivelMRM(5);
    }//GEN-LAST:event_mrmNivel5ActionPerformed

    private void mrmNivel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrmNivel4ActionPerformed
        // TODO add your handling code here:
        setNivelMRM(4);
    }//GEN-LAST:event_mrmNivel4ActionPerformed

    private void mrmNivel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrmNivel3ActionPerformed
        // TODO add your handling code here:
        setNivelMRM(3);
    }//GEN-LAST:event_mrmNivel3ActionPerformed

    private void mrmNivel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrmNivel2ActionPerformed
        // TODO add your handling code here:
        setNivelMRM(2);
    }//GEN-LAST:event_mrmNivel2ActionPerformed

    private void mrmNivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrmNivel1ActionPerformed
        // TODO add your handling code here:
        setNivelMRM(1);
    }//GEN-LAST:event_mrmNivel1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        int index = menu.getSelectedIndex(); 

        if(index-1 == 0)
        {
            back.setVisible(false);
            next.setVisible(false);
        }
        
        if(index == 2 && getAONivel() != 0)
                next.setEnabled(true);
            if(index == 3 && getNivelMRV() != 0)
                next.setEnabled(true);
            if(index == 4 && getNivelMRM() != 0)
                next.setEnabled(true);
        
        menu.setSelectedIndex(index-1);
    }//GEN-LAST:event_backActionPerformed

    private void backMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuActionPerformed
        // TODO add your handling code here:
        menu.setSelectedIndex(0);
        next.setVisible(false);
        back.setVisible(false);
        
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        
        setAONivel(0);
        setNivelMRV(0);
        setNivelMRM(0);
    }//GEN-LAST:event_backMenuActionPerformed

    private void mrvNivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrvNivel1ActionPerformed
        // TODO add your handling code here:
        setNivelMRV(1);
    }//GEN-LAST:event_mrvNivel1ActionPerformed

    private void mrvNivel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrvNivel2ActionPerformed
        // TODO add your handling code here:
        setNivelMRV(2);
    }//GEN-LAST:event_mrvNivel2ActionPerformed

    private void mrvNivel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrvNivel3ActionPerformed
        // TODO add your handling code here:
        setNivelMRV(3);
    }//GEN-LAST:event_mrvNivel3ActionPerformed

    private void mrvNivel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrvNivel4ActionPerformed
        // TODO add your handling code here:
        setNivelMRV(4);
    }//GEN-LAST:event_mrvNivel4ActionPerformed

    private void mrvNivel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrvNivel5ActionPerformed
        // TODO add your handling code here:
        setNivelMRV(5);
    }//GEN-LAST:event_mrvNivel5ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aoNivel1;
    private javax.swing.JRadioButton aoNivel2;
    private javax.swing.JRadioButton aoNivel3;
    private javax.swing.JRadioButton aoNivel4;
    private javax.swing.JButton back;
    private javax.swing.JButton backMenu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel classificacao;
    private javax.swing.JButton fazerEscalar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JRadioButton mrmNivel1;
    private javax.swing.JRadioButton mrmNivel2;
    private javax.swing.JRadioButton mrmNivel3;
    private javax.swing.JRadioButton mrmNivel4;
    private javax.swing.JRadioButton mrmNivel5;
    private javax.swing.JRadioButton mrmNivel6;
    private javax.swing.JRadioButton mrvNivel1;
    private javax.swing.JRadioButton mrvNivel2;
    private javax.swing.JRadioButton mrvNivel3;
    private javax.swing.JRadioButton mrvNivel4;
    private javax.swing.JRadioButton mrvNivel5;
    private javax.swing.JButton next;
    private javax.swing.JButton sair;
    private javax.swing.JLabel situacao;
    private javax.swing.JLabel totalPonto;
    // End of variables declaration//GEN-END:variables
}
